// Generate the Dart "glue": a program that imports the user's plain top-level
// functions and binds each into a `(Map input) => fn(named: input['named'])`
// wrapper — named binding with no reflection, extras dropped — then runs the IR.
// The function names and parameters come from the analyzer (never regex).

import 'package:codengine_analyzer/codengine_analyzer.dart';
import 'package:codengine_core/codengine_core.dart';
import 'package:path/path.dart' as p;

/// Build the glue source for `modules` (`{module: {files, root}}`), to be written
/// at `glueDir` (so relative imports resolve).
String generateGlue(Map<String, dynamic> modules, String glueDir) {
  final imports = StringBuffer()
    ..writeln("// GENERATED by codengine-generator-dart. Do not edit.")
    ..writeln("import 'dart:convert';")
    ..writeln("import 'dart:io';")
    ..writeln("import 'package:codengine_runner/codengine_runner.dart';")
    ..writeln("import 'package:codengine_loader/codengine_loader.dart' show mergeFunctions;");

  final aliasByFile = <String, String>{};
  final moduleEntries = StringBuffer();

  modules.forEach((module, spec) {
    final files = ((spec as Map)['files'] as List).cast<String>();
    final fileEntries = StringBuffer();
    for (final file in files) {
      final alias = aliasByFile.putIfAbsent(file, () {
        final name = 'f${aliasByFile.length}';
        imports.writeln("import ${_str(p.relative(file, from: glueDir))} as $name;");
        return name;
      });
      final definitions = (analyzeSource(file)['definitions'] as List).cast<TaskDefinition>();
      final wrappers = definitions
          .map((def) => "        '${def['name']}': ${_wrapper(alias, def)},")
          .join('\n');
      fileEntries.writeln("      (${_str(file)}, <String, TaskFunction>{\n$wrappers\n      }),");
    }
    moduleEntries.writeln("  '$module': mergeFunctions([\n$fileEntries    ]),");
  });

  return '''
${imports.toString()}
Future<void> main() async {
  final request = jsonDecode(await stdin.transform(utf8.decoder).join());
  final functions = <String, Map<String, TaskFunction>>{
${moduleEntries.toString()}  };
  final result = run(
    request['workflows'] as List,
    functions,
    request['entry'] as String,
    (request['input'] as Map).cast<String, dynamic>(),
  );
  stdout.write(jsonEncode({'result': result}));
}
''';
}

String _wrapper(String alias, Map def) {
  final fn = def['name'];
  final params = (def['params'] as List).cast<Map>();
  if (params.isNotEmpty) {
    final args = params.map((param) => "${param['name']}: input['${param['name']}']").join(', ');
    return "(Map<String, dynamic> input) => $alias.$fn($args)";
  }
  if (def['acceptsExtra'] == true) {
    return "(Map<String, dynamic> input) => $alias.$fn(input)"; // whole-map function
  }
  return "(Map<String, dynamic> input) => $alias.$fn()";
}

// A safe single-quoted Dart string literal.
String _str(String value) => "'${value.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";
